name: 'Next.js bundle analyzer'
inputs:
  workflow-id:
    description: 'Workflow ID containing this step'
  base-branch:
    description: 'Base branch of the repo (master or main)'
    default: master
  working-directory:
    description: 'Directory containing built files'
    default: ''
  bundle-size-issue-number:
    description: 'The number of the issue displaying current bundle sizes'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
