name: 'Next.js bundle analyzer'
description: 'Measure Next.js app page sizes and notify of changes in PR comments'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  working-directory:
    description: 'Directory containing built files'
    required: false
    default: ''
  comment-strategy:
    description: >
      The desired behavior for commenting on Pull Requests.

      Available options:
        always: Always comment on PRs, even if it's just to say there are no significant changes.
        skip-insignificant: Skip commenting on PRs if there are no signficant changes in page sizes.
    required: false
    default: 'always'
  create-issue:
    description: >
      Configures whether to create the bundle size summary issue.

      Available options:
        true
        false
    default: 'true'
  github-token:
    description: 'The GitHub token used to authenticate with the GitHub API.'
    required: false
    default: ${{ github.token }}
